### ISSUE TITLE
Problem with devcontainer.json

### ISSUE THREAD

**Issue by trukhinyuri** [davidgasquez/dbt-devcontainer#3]
devcontainer.json does not build in JetBrains IDE 2024.1 and VSCode.

JetBrains IDE Welcome screen -> DevContainers -> New DevContainer (from VCS Project, Docker must be installed.) Insert the git@ link of the repository with devcontainer.json. -> "Build container and Continue"
<img width="1017" alt="image" src="https://github.com/davidgasquez/dbt-devcontainer/assets/1245379/19ca670d-7182-435f-8865-ac03325009d0">
<img width="1404" alt="image" src="https://github.com/davidgasquez/dbt-devcontainer/assets/1245379/0eb9f388-7916-4f24-9737-52042b53e14b">

**Comment by davidgasquez** [comment]
Not sure what is going on there... is there a way to get better logs?
